apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-deployment
  namespace: k8s-program
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resource
  template:
    metadata:
      labels:
        app: resource
    spec:
      containers:
        - name: resource
          image: mojtaaba/my-resource-service
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RESOURCE_PORT
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RESOURCE_MONGO_URI
            - name: SONG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RESOURCE_SONG_SERVICE_URL
