apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resource-mongodb-statefulset
  namespace: k8s-program
spec:
  serviceName: resource-mongodb-service
  replicas: 1
  selector:
    matchLabels:
      app: resource-mongodb
  template:
    metadata:
      labels:
        app: resource-mongodb
    spec:
      containers:
      - name: resource-mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: resource-mongodb-data
          mountPath: /data/db
        - name: config
          mountPath: "/docker-entrypoint-initdb.d"
          readOnly: true
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 15
          periodSeconds: 20
        startupProbe:
          tcpSocket:
            port: 27017
          failureThreshold: 3
          periodSeconds: 30
      volumes:
      - name: config
        configMap:
          name: resource-db-creation
          items:
          - key: "mongo-init.js"
            path: "mongo-init.js"
  volumeClaimTemplates:
  - metadata:
      name: resource-mongodb-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "hostpath"
      resources:
        requests:
          storage: 1Gi
