# This file was created to just prove that I know how to create Secret Object
# However, Since the provided project code did not use any password,I am not going to use these secrets
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: k8s-program
type: Opaque
data:
  username: ZHVtbXktdXNlcm5hbWU=
  password: ZHVtbXktcGFzc3dvcmQ=
