apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /api/resources$1$2
  name: resource-ingress
  namespace: k8s-program
spec:
  ingressClassName: nginx
  rules:
  - host: resource.com
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: resource-service
            port:
              number: 3000

