apiVersion: v1
kind: Service
metadata:
  name: resource-mongodb-service
  namespace: k8s-program
spec:
  selector:
    app: resource-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None
