apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-deployment
  namespace: k8s-program
spec:
  replicas: 2
  selector:
    matchLabels:
      app: song
  template:
    metadata:
      labels:
        app: song
    spec:
      containers:
      - name: song
        image: mojtaaba/my-song-service:v2
        ports:
        - containerPort: 3001
        readinessProbe:
          httpGet:
            path: /api/songs/ready
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/songs/live
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 15
        startupProbe:
          httpGet:
            path: /api/songs/status
            port: 3001
          failureThreshold: 30
          periodSeconds: 10
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SONG_PORT
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SONG_MONGO_URI
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data-pvc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
