apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
  namespace: k8s-program
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
