apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-deployment
  namespace: k8s-program
spec:
  replicas: 2
  selector:
    matchLabels:
      app: song
  template:
    metadata:
      labels:
        app: song
    spec:
      containers:
        - name: song
          image: mojtaaba/my-song-service
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: MONGO_URI
              value: "mongodb://mongodb-service:27017/song"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
