apiVersion: v1
kind: Service
metadata:
  name: song-mongodb-service
  namespace: k8s-program
spec:
  selector:
    app: song-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None
